apiVersion: v2
name: texas
description: A high-performance, extensible QQ Bot framework based on NapCat / OneBot 11 (Node.js)
type: application
version: 1.4.0
appVersion: '1.4.0'
keywords:
  - qq-bot
  - napcat
  - onebot
  - fastapi
home: https://github.com/AkariRin/texas
maintainers:
  - name: Texas Team

dependencies:
  - name: postgresql
    version: '~16.4'
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: '~20.6'
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: redis
    version: '~20.6'
    repository: https://charts.bitnami.com/bitnami
    alias: redis-cache
    condition: redis-cache.enabled
